### ISSUE TITLE
(Feature request) Reboot back to satiator  menu

### ISSUE THREAD

**Issue by Chrs2021** [satiator/satiator-menu#16]
Sorry if this is already a thing but is it possible go back to the satiator menu without powering off the system and turning it back on?

**Comment by slinga-homebrew** [comment]
Yes I added a "Exit to CD Player" option and tweaked the "Reboot" option in SGC 3.5.0. What version of SGC are you using? Is it not working?
![shot](https://user-images.githubusercontent.com/58894244/104406579-982e6a00-552d-11eb-9b9a-bedeb04c6dfe.png)

**Comment by slinga-homebrew** [comment]
Here's how I'm reboot from SGC: 

```
/** @brief Restart the Saturn
 *  @warning Doesn't work in Yabause
 */
static  __jo_force_inline void jo_core_restart_saturn(void)
{
    jo_smpc_begin_command();
    jo_smpc_end_command(SystemReset);
}
```

**Comment by Chrs2021** [comment]
Sorry I should clarify a bit more. — I meant after choosing a game. Is there a way to virtually eject the selected game and go back to the satiator menu without having to fully power cycle the system.

**Comment by robertragno** [comment]
This is partially fixed in current version(60) if you have an Action Replay that has been flashed with the most recent AR patch(3) to enable soft reset to menu. A later fix may implement this so that you don't need an AR.

**Comment by Chrs2021** [comment]
Like every semi-long time saturn owner i do have an ar cart but it's flashed with pseudo saturn kai. I will look in to this though thank you for the protip @robertragno

**Comment by abrasive** [comment]
Satiator Menu Kai now supports this better than I could hope to, so closing this.
