### ISSUE TITLE
(Feature Request) - Change back button mapping from 'C' to 'B', paging to d-pad left and right, and/or possibly add options for paging  button config.

### ISSUE THREAD

**Issue by robertragno** [satiator/satiator-menu#18]
Currently 'C' is used to return in the menu. Nearly all other Saturn official/unofficial software use 'B' for this. Suggest changing this mapping to 'B'. 

The paging of the file list uses the L and R buttons currently. Most other UI's utilize Left and Right on the d-pad to perform this. Suggest changing to this to standardize UI behavior. A more advanced fix would be to create an Options screen to make this user configurable. It could also have AR tools, firmware/serial/menu versions displayed, other configurable options, etc.

**Comment by Peredonov** [comment]
This is an important request. Many similar devices and UIs have a "swap select/cancel buttons" settings that address this kind of issue.

**Comment by abrasive** [comment]
Thanks for the request. It's a bit late to change this up on existing users, but I will consider it if I add a setting interface in future
