### ISSUE TITLE
(Feature Request) - Add option to return to multiplayer menu

### ISSUE THREAD

**Issue by robertragno** [satiator/satiator-menu#20]
Currently with the new AR patch the only way to return to the multiplayer menu is to open the CD lid on boot. Suggest adding an option to the menu to do the same thing for ease of use. This is especially relevant until the PSK/Red 3in1/4in1 non-AR carts bug (booting to the multiplayer isn't possible since the AR patched version interrupts this when you open the CD lid while booting and instead goes to a black screen) is fixed.

**Comment by abrasive** [comment]
AR patch has been removed due to the intractability of patching that ancient code.
