### ISSUE TITLE
Feature Request: keeping the whole skippable Saturn boot logo

### ISSUE THREAD

**Issue by handsaway** [satiator/satiator-menu#23]
When booting the console with no Satiator plugged, the sequence is:
[skippable animation intro] > [static Saturn logo] > [CD-game running]
By "skippable animation intro", I mean the intro sequence where we see the grey polygons merging together, ending with the Saturn logo screen (i.e., the next step in my description: "static Saturn logo").

When booting the console with a Satiator plugged, the sequence is:
[static Saturn logo] > [Multiplayer view] > [Satiator folder menu]
What I mean is we directly see the Saturn logo screen, but the animation is skipped as if we were holding a button on the controller.

Is it possible to keep the original sequence, while using the Satiator? We would then get:
[skippable animation intro] > [static Saturn logo] > [Multiplayer view] > [Satiator folder menu]

Maybe it is impossible due to how the Satiator booting works?
Please delete if it does not make sense.

**Comment by abrasive** [comment]
Hi! I'm sorry, it's not possible in general - as you suspected, the Satiator only gets control of the boot sequence fairly late. Thanks for asking though, it would have been nice to have :-)
