### ISSUE TITLE
Suddenly Slow Transfer Speeds

### ISSUE THREAD

**Issue by slinga-homebrew** [satiator/satiator-menu#9]
User mantixero from Discord is reporting a sudden decrease in the speed of transferring a save with Save Game Copier. What's weird is that the first transfer takes ~90 seconds regardless of save size. Every write after that takes ~1 second as expected. After waiting 90 seconds the save size is correct so it's not like SGC is writing the wrong amount. 

The first file is < 2048 bytes so it should be a single write operation. I'm stumped on how to debug this. 

"I went ahead and recorded the total time for save transfers to the Satiator to later compare with the time spent actually writing data.

In the first trial, I copied a 48-byte Rockman X3 save from internal memory to the SD card, which took ~91 seconds (good guess on my part, woo!), and then transferred a 4388-byte Dracula X save, which took 1 second. I then deleted the saves from the Satiator and rebooted the Saturn.

In the second trial, I started by transferring the 4388-byte Dracula X save, which also took ~91 seconds, and then transferred the 48-byte Rockman X3 save, which took 1 second.

All transfers used to take 1 second, so I'm confused as to what changed without updating either Save Game Copier or Satiator firmware, and without adding games to the SD card (it had about 100MB free from the start). The only things I can think of that are different are 1) There are now more saves in my Saturn's internal memory (I think the Saturn BIOS said I had 83 blocks free), whereas I had almost no internal saves at the start of my SGC usage, and 2) There is now a Pseudo Saturn (settings?) save file in internal memory that I can see with SGC, but can't see when I plug the SD card into my PC. I'll try deleting the Pseudo Saturn settings file first and see if that helps, and then delete all internal saves to see if that helps."

**Comment by abrasive** [comment]
I suspect this was a corrupt SD based on the description. No futher reports appeared, so closing
